Feat/perfil
ignaciovillela/iTrek-front pull request #19
Opened 2024-11-02 19:12 UTC by Die4uSixx

Se agregan atributos faltantes de perfil y se vizualizan en perfil de usuario.

2024-11-06 18:31 UTC, ignaciovillela requested changes

2024-11-06 18:31 UTC, ignaciovillela commented on lib/pages/usuario/login.dart
Por qué todos estos cambios en el login?

2024-11-06 18:31 UTC, ignaciovillela commented on lib/pages/usuario/usuarioPerfil.dart
> +    final imagenPerfil = await db.values.get('usuario_imagen_perfil') as String?;
Deberían tener el formato `final firstName = await db.values.get(db.values.first_name) as String?;`

2024-11-06 18:31 UTC, ignaciovillela commented on lib/pages/usuario/usuarioPerfil.dart
> +  Future<void> _updateProfile() async {
En general está bien la función, pero debes usar `makeRequest` en vez del `http.put`.
El username, la password y el email no se deberían poder cambiar.

2024-11-06 18:31 UTC, ignaciovillela commented on lib/pages/usuario/usuarioPerfil.dart
> +        await db.values.create('username', responseData['username']);
Para setear los datos de usuario que vienen del backend puedes usar `db.values.createLoginData(responseData)`.
También aplica al login

2024-11-06 18:31 UTC, ignaciovillela commented on pubspec.yaml
> +
Eliminar estos espacios en blanco

2024-11-06 19:10 UTC, ignaciovillela commented on lib/request.dart
> +const UPDATE_USER = 'api/users/update-profile/';
ya existe en la sección de usuario, se llama `USER_UPDATE`

2024-11-07 12:22 UTC, Die4uSixx commented on lib/pages/usuario/login.dart
Son para agregar los campos faltantes en la db.dart, al momento de loguearse

2024-11-07 12:35 UTC, Die4uSixx commented on lib/pages/usuario/usuarioPerfil.dart
> +    final imagenPerfil = await db.values.get('usuario_imagen_perfil') as String?;
cual es el problema ?, el tipo de variable final?

2024-11-07 12:36 UTC, Die4uSixx commented on lib/pages/usuario/usuarioPerfil.dart
> +  Future<void> _updateProfile() async {
la probare

2024-11-07 12:37 UTC, Die4uSixx commented on lib/pages/usuario/usuarioPerfil.dart
> +        await db.values.create('username', responseData['username']);
lo intentare, no tenia ni idea.

2024-11-07 12:37 UTC, Die4uSixx commented on pubspec.yaml
> +
ok

2024-11-07 12:38 UTC, Die4uSixx commented on lib/request.dart
> +const UPDATE_USER = 'api/users/update-profile/';
okis, pero como no tenía actualizado mi rama, no aparecia

2024-11-07 13:15 UTC, ignaciovillela commented on lib/pages/usuario/usuarioPerfil.dart
> +    final imagenPerfil = await db.values.get('usuario_imagen_perfil') as String?;
los string que le pasas al get, deberían ser constantes

2024-11-07 18:25 UTC, ignaciovillela approved these changes

2024-11-07 18:26 UTC, merged